version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=abbadnaufal
    ports:
      - '5432:5432'
    volumes: 
      - postgres:/var/lib/postgresql/data

  rabbit:
    image: rabbitmq:3.10-management
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "5672:5672"
      - "15672:15672"
volumes:
  postgres:
    driver: local